"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def sum_of_even_fib_numbers(max):
    fib = [1, 2]
    while fib[-1] < max:
        if fib[-2] + fib[-1] > max:
            break

        fib.append(fib[-2] + fib[-1])

    return sum([n for n in fib if n % 2 == 0])


print(sum_of_even_fib_numbers(4000000))